"""HLL RCON command schema — based on MarechJ/hll_rcon_tool API surface."""


def get_commands():
    from app.plugins.base import CommandDef, CommandParam

    return [
        # ── SERVER INFO ────────────────────────────────────────────────
        CommandDef(
            name="GetServerInformation",
            description="Query server information (session, players, maprotation, etc.)",
            category="SERVER_INFO",
            params=[
                CommandParam(name="Name", type="enum", required=True,
                             description="Info type to query",
                             choices=["session", "players", "player", "maprotation",
                                         "mapsequence", "vipplayers", "bannedwords"]),
                CommandParam(name="Value", type="string", required=False,
                             description="Optional filter value (e.g. player_id for player lookup)"),
            ],
            example='GetServerInformation {"Name":"session","Value":""}',
        ),
        CommandDef(
            name="GetAdminLog",
            description="Retrieve server log entries",
            category="SERVER_INFO",
            params=[
                CommandParam(name="LogBackTrackTime", type="integer", required=True,
                             description="Seconds to look back"),
                CommandParam(name="Filters", type="string", required=False,
                             description="Log filter string"),
            ],
            example='GetAdminLog {"LogBackTrackTime":3600,"Filters":""}',
        ),
        CommandDef(name="GetAdminGroups", description="List admin groups", category="SERVER_INFO",
                   example="GetAdminGroups"),
        CommandDef(name="GetAdminUsers", description="List admin users", category="SERVER_INFO",
                   example="GetAdminUsers"),
        CommandDef(name="GetTemporaryBans", description="List temp bans", category="SERVER_INFO",
                   example="GetTemporaryBans"),
        CommandDef(name="GetPermanentBans", description="List permanent bans", category="SERVER_INFO",
                   example="GetPermanentBans"),
        CommandDef(name="GetClientReferenceData", description="Get reference data (maps, etc.)",
                   category="SERVER_INFO",
                   params=[CommandParam(name="DataType", type="string", required=True,
                                       description="e.g. AddMapToRotation")],
                   example='GetClientReferenceData "AddMapToRotation"'),

        # ── SERVER SETTINGS ────────────────────────────────────────────
        CommandDef(name="GetAutoBalanceEnabled", description="Get autobalance status", category="SERVER_SETTINGS",
                   example="GetAutoBalanceEnabled"),
        CommandDef(name="GetAutoBalanceThreshold", description="Get autobalance threshold", category="SERVER_SETTINGS",
                   example="GetAutoBalanceThreshold"),
        CommandDef(name="GetTeamSwitchCooldown", description="Get team switch cooldown", category="SERVER_SETTINGS",
                   example="GetTeamSwitchCooldown"),
        CommandDef(name="GetKickIdleDuration", description="Get idle kick duration", category="SERVER_SETTINGS",
                   example="GetKickIdleDuration"),
        CommandDef(name="GetHighPingThreshold", description="Get high ping kick threshold", category="SERVER_SETTINGS",
                   example="GetHighPingThreshold"),
        CommandDef(name="GetVoteKickEnabled", description="Get vote kick enabled status", category="SERVER_SETTINGS",
                   example="GetVoteKickEnabled"),
        CommandDef(name="GetVoteKickThreshold", description="Get vote kick thresholds", category="SERVER_SETTINGS",
                   example="GetVoteKickThreshold"),
        CommandDef(
            name="SetAutoBalanceEnabled",
            description="Enable/disable autobalance",
            category="SERVER_SETTINGS",
            params=[CommandParam(name="Enabled", type="boolean", required=True,
                                 description="true/false")],
            example='SetAutoBalanceEnabled {"Enabled":true}',
        ),
        CommandDef(
            name="SetAutoBalanceThreshold",
            description="Set autobalance threshold",
            category="SERVER_SETTINGS",
            params=[CommandParam(name="Threshold", type="integer", required=True,
                                 description="Player count difference threshold")],
            example='SetAutoBalanceThreshold {"Threshold":3}',
        ),
        CommandDef(
            name="SetTeamSwitchCooldown",
            description="Set team switch cooldown (minutes)",
            category="SERVER_SETTINGS",
            params=[CommandParam(name="Cooldown", type="integer", required=True,
                                 description="Cooldown in minutes")],
            example='SetTeamSwitchCooldown {"Cooldown":15}',
        ),
        CommandDef(
            name="SetIdleKickDuration",
            description="Set idle kick duration (minutes)",
            category="SERVER_SETTINGS",
            params=[CommandParam(name="IdleTimeoutMinutes", type="integer", required=True,
                                 description="Minutes before idle kick")],
            example='SetIdleKickDuration {"IdleTimeoutMinutes":10}',
        ),
        CommandDef(
            name="SetHighPingThreshold",
            description="Set high ping kick threshold (ms)",
            category="SERVER_SETTINGS",
            params=[CommandParam(name="Threshold", type="integer", required=True,
                                 description="Ping threshold in ms")],
            example='SetHighPingThreshold {"Threshold":500}',
        ),
        CommandDef(
            name="SetVoteKickEnabled",
            description="Enable/disable vote kick",
            category="SERVER_SETTINGS",
            params=[CommandParam(name="Enabled", type="boolean", required=True,
                                 description="true/false")],
            example='SetVoteKickEnabled {"Enabled":true}',
        ),
        CommandDef(
            name="SetVoteKickThreshold",
            description="Set vote kick thresholds",
            category="SERVER_SETTINGS",
            params=[CommandParam(name="Threshold", type="string", required=True,
                                 description="Threshold list e.g. '10,1,25,2'")],
            example='SetVoteKickThreshold {"Threshold":"10,1,25,2"}',
        ),
        CommandDef(name="ResetVoteKickThreshold", description="Reset vote kick thresholds to default",
                   category="SERVER_SETTINGS", example="ResetVoteKickThreshold"),
        CommandDef(
            name="SetMaxQueuedPlayers",
            description="Set max queue length",
            category="SERVER_SETTINGS",
            params=[CommandParam(name="MaxQueuedPlayers", type="integer", required=True,
                                 description="Max players in queue")],
            example='SetMaxQueuedPlayers {"MaxQueuedPlayers":6}',
        ),
        CommandDef(
            name="SetVipSlotCount",
            description="Set number of VIP reserved slots",
            category="SERVER_SETTINGS",
            params=[CommandParam(name="VipSlotCount", type="integer", required=True,
                                 description="Number of VIP slots")],
            example='SetVipSlotCount {"VipSlotCount":2}',
        ),
        CommandDef(
            name="SetMapShuffleEnabled",
            description="Enable/disable map shuffle",
            category="SERVER_SETTINGS",
            params=[CommandParam(name="Enabled", type="boolean", required=True,
                                 description="true/false")],
            example='SetMapShuffleEnabled {"Enabled":true}',
        ),
        CommandDef(
            name="SetDynamicWeatherEnabled",
            description="Enable/disable dynamic weather",
            category="SERVER_SETTINGS",
            params=[CommandParam(name="Enabled", type="boolean", required=True,
                                 description="true/false")],
            example='SetDynamicWeatherEnabled {"Enabled":true}',
        ),
        CommandDef(
            name="SetWelcomeMessage",
            description="Set the server welcome message",
            category="SERVER_SETTINGS",
            params=[CommandParam(name="Message", type="string", required=True,
                                 description="Welcome message text")],
            example='SetWelcomeMessage {"Message":"Welcome!"}',
        ),
        CommandDef(
            name="ServerBroadcast",
            description="Broadcast a message to all players",
            category="SERVER_SETTINGS",
            params=[CommandParam(name="Message", type="string", required=True,
                                 description="Broadcast message")],
            example='ServerBroadcast {"Message":"Server restart in 5 minutes"}',
        ),

        # ── MAP MANAGEMENT ─────────────────────────────────────────────
        CommandDef(
            name="ChangeMap",
            description="Change the current map immediately",
            category="MAP_MGMT",
            params=[CommandParam(name="MapName", type="string", required=True,
                                 description="Map ID to switch to")],
            example='ChangeMap {"MapName":"carentan_offensive_ger"}',
        ),
        CommandDef(
            name="AddMapToRotation",
            description="Add a map to the rotation",
            category="MAP_MGMT",
            params=[
                CommandParam(name="MapName", type="string", required=True, description="Map ID"),
                CommandParam(name="AfterMapName", type="string", required=False,
                             description="Insert after this map"),
                CommandParam(name="AfterMapRepetition", type="integer", required=False,
                             description="Repetition index of anchor map"),
            ],
            example='AddMapToRotation {"MapName":"hill400_warfare"}',
        ),
        CommandDef(
            name="RemoveMapFromRotation",
            description="Remove a map from the rotation",
            category="MAP_MGMT",
            params=[
                CommandParam(name="MapName", type="string", required=True, description="Map ID"),
                CommandParam(name="MapRepetition", type="integer", required=False,
                             description="Repetition index if map appears multiple times"),
            ],
            example='RemoveMapFromRotation {"MapName":"hill400_warfare"}',
        ),
        CommandDef(
            name="AddMapToSequence",
            description="Add a map to the sequence at index",
            category="MAP_MGMT",
            params=[
                CommandParam(name="MapName", type="string", required=True, description="Map ID"),
                CommandParam(name="SequenceIndex", type="integer", required=True,
                             description="Position in sequence"),
            ],
            example='AddMapToSequence {"MapName":"hill400_warfare","SequenceIndex":0}',
        ),
        CommandDef(
            name="RemoveMapFromSequence",
            description="Remove a map from the sequence",
            category="MAP_MGMT",
            params=[
                CommandParam(name="MapName", type="string", required=True, description="Map ID"),
                CommandParam(name="SequenceIndex", type="integer", required=True,
                             description="Index of map in sequence"),
            ],
            example='RemoveMapFromSequence {"MapName":"hill400_warfare","SequenceIndex":0}',
        ),
        CommandDef(
            name="MoveMapInSequence",
            description="Move a map to a new position in the sequence",
            category="MAP_MGMT",
            params=[
                CommandParam(name="MapName", type="string", required=True, description="Map ID"),
                CommandParam(name="CurrentSequenceIndex", type="integer", required=True,
                             description="Current index"),
                CommandParam(name="NewSequenceIndex", type="integer", required=True,
                             description="Target index"),
            ],
            example='MoveMapInSequence {"MapName":"hill400_warfare","CurrentSequenceIndex":0,"NewSequenceIndex":2}',
        ),
        CommandDef(
            name="SetSectorLayout",
            description="Set sector layout for current map",
            category="MAP_MGMT",
            params=[CommandParam(name="SectorLayout", type="string", required=True,
                                 description="Sector layout JSON")],
            example='SetSectorLayout {"SectorLayout":"..."}',
        ),

        # ── TIMERS ─────────────────────────────────────────────────────
        CommandDef(
            name="SetMatchTimer",
            description="Set match timer duration",
            category="TIMERS",
            params=[CommandParam(name="TimerSeconds", type="integer", required=True,
                                 description="Match duration in seconds")],
            example='SetMatchTimer {"TimerSeconds":5400}',
        ),
        CommandDef(name="RemoveMatchTimer", description="Remove/reset match timer",
                   category="TIMERS", example="RemoveMatchTimer"),
        CommandDef(
            name="SetWarmupTimer",
            description="Set warmup timer duration",
            category="TIMERS",
            params=[CommandParam(name="TimerSeconds", type="integer", required=True,
                                 description="Warmup duration in seconds")],
            example='SetWarmupTimer {"TimerSeconds":300}',
        ),
        CommandDef(name="RemoveWarmupTimer", description="Remove/reset warmup timer",
                   category="TIMERS", example="RemoveWarmupTimer"),

        # ── PLAYER ACTIONS ─────────────────────────────────────────────
        CommandDef(
            name="PunishPlayer",
            description="Punish (warn) a player",
            category="PLAYER_ACTIONS",
            params=[
                CommandParam(name="PlayerId", type="string", required=True,
                             description="Player Steam ID"),
                CommandParam(name="Reason", type="string", required=True,
                             description="Reason shown to player"),
            ],
            example='PunishPlayer {"PlayerId":"76561198012345678","Reason":"Teamkilling"}',
        ),
        CommandDef(
            name="KickPlayer",
            description="Kick a player from the server",
            category="PLAYER_ACTIONS",
            params=[
                CommandParam(name="PlayerId", type="string", required=True,
                             description="Player Steam ID"),
                CommandParam(name="Reason", type="string", required=True,
                             description="Kick reason"),
            ],
            example='KickPlayer {"PlayerId":"76561198012345678","Reason":"Breaking rules"}',
        ),
        CommandDef(
            name="TemporaryBanPlayer",
            description="Temporarily ban a player",
            category="PLAYER_ACTIONS",
            params=[
                CommandParam(name="PlayerId", type="string", required=True,
                             description="Player Steam ID"),
                CommandParam(name="Duration", type="integer", required=True,
                             description="Ban duration in hours"),
                CommandParam(name="Reason", type="string", required=True,
                             description="Ban reason"),
                CommandParam(name="AdminName", type="string", required=False,
                             description="Admin performing the ban"),
            ],
            example='TemporaryBanPlayer {"PlayerId":"76561198012345678","Duration":24,"Reason":"Cheating","AdminName":"Admin"}',
        ),
        CommandDef(
            name="PermanentBanPlayer",
            description="Permanently ban a player",
            category="PLAYER_ACTIONS",
            params=[
                CommandParam(name="PlayerId", type="string", required=True,
                             description="Player Steam ID"),
                CommandParam(name="Reason", type="string", required=True,
                             description="Ban reason"),
                CommandParam(name="AdminName", type="string", required=False,
                             description="Admin performing the ban"),
            ],
            example='PermanentBanPlayer {"PlayerId":"76561198012345678","Reason":"Hacking","AdminName":"Admin"}',
        ),
        CommandDef(
            name="RemovePlayerFromPlatoon",
            description="Remove a player from their squad",
            category="PLAYER_ACTIONS",
            params=[
                CommandParam(name="PlayerId", type="string", required=True,
                             description="Player Steam ID"),
                CommandParam(name="Reason", type="string", required=True,
                             description="Reason"),
            ],
            example='RemovePlayerFromPlatoon {"PlayerId":"76561198012345678","Reason":"AFK"}',
        ),
        CommandDef(
            name="ForceTeamSwitch",
            description="Force team switch for a player (0=on death, 1=now)",
            category="PLAYER_ACTIONS",
            params=[
                CommandParam(name="PlayerId", type="string", required=True,
                             description="Player Steam ID"),
                CommandParam(name="ForceMode", type="enum", required=True,
                             description="0=on next death, 1=immediately",
                             choices=["0", "1"]),
            ],
            example='ForceTeamSwitch {"PlayerId":"76561198012345678","ForceMode":1}',
        ),
        CommandDef(
            name="MessagePlayer",
            description="Send a private message to a player",
            category="PLAYER_ACTIONS",
            params=[
                CommandParam(name="PlayerId", type="string", required=True,
                             description="Player Steam ID"),
                CommandParam(name="Message", type="string", required=True,
                             description="Message text"),
            ],
            example='MessagePlayer {"PlayerId":"76561198012345678","Message":"Please follow the rules"}',
        ),

        # ── ADMIN / VIP MANAGEMENT ─────────────────────────────────────
        CommandDef(
            name="AddAdmin",
            description="Add a player as admin",
            category="ADMIN_MGMT",
            params=[
                CommandParam(name="PlayerId", type="string", required=True,
                             description="Player Steam ID"),
                CommandParam(name="AdminGroup", type="string", required=True,
                             description="Admin group name"),
                CommandParam(name="Comment", type="string", required=False,
                             description="Comment/note"),
            ],
            example='AddAdmin {"PlayerId":"76561198012345678","AdminGroup":"Moderator","Comment":"Trusted player"}',
        ),
        CommandDef(
            name="RemoveAdmin",
            description="Remove a player's admin status",
            category="ADMIN_MGMT",
            params=[CommandParam(name="PlayerId", type="string", required=True,
                                 description="Player Steam ID")],
            example='RemoveAdmin {"PlayerId":"76561198012345678"}',
        ),
        CommandDef(
            name="AddVip",
            description="Add a VIP player",
            category="ADMIN_MGMT",
            params=[
                CommandParam(name="PlayerId", type="string", required=True,
                             description="Player Steam ID"),
                CommandParam(name="Comment", type="string", required=False,
                             description="Comment/note"),
            ],
            example='AddVip {"PlayerId":"76561198012345678","Comment":"Donor"}',
        ),
        CommandDef(
            name="RemoveVip",
            description="Remove VIP status from a player",
            category="ADMIN_MGMT",
            params=[CommandParam(name="PlayerId", type="string", required=True,
                                 description="Player Steam ID")],
            example='RemoveVip {"PlayerId":"76561198012345678"}',
        ),

        # ── BANNED WORDS ───────────────────────────────────────────────
        CommandDef(
            name="AddBannedWords",
            description="Add words to the profanity filter",
            category="MODERATION",
            params=[CommandParam(name="BannedWords", type="string", required=True,
                                 description="Comma-separated list of words")],
            example='AddBannedWords {"BannedWords":["word1","word2"]}',
        ),
        CommandDef(
            name="RemoveBannedWords",
            description="Remove words from the profanity filter",
            category="MODERATION",
            params=[CommandParam(name="BannedWords", type="string", required=True,
                                 description="Comma-separated list of words to remove")],
            example='RemoveBannedWords {"BannedWords":["word1"]}',
        ),
    ]
